spring.application.name=JobPortal-Backend

# ================= DATABASE =================
spring.datasource.url=jdbc:postgresql://localhost:5432/JobDb
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# ================= SERVER =================
server.port=8081
spring.main.allow-bean-definition-overriding=true
spring.main.web-application-type=servlet

# ================= FILE UPLOAD =================
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=6MB

# ================= MAIL =================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${EMAIL_USERNAME}
spring.mail.password=${EMAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ================= CACHE (CAFFEINE) =================
spring.cache.type=caffeine
spring.cache.cache-names=candidateMatches
spring.cache.caffeine.spec=maximumSize=200,expireAfterWrite=10m

# ================= LOGGING =================
logging.level.root=INFO
logging.level.com.aman=INFO
logging.level.org.springframework.security=WARN
logging.level.org.hibernate.SQL=WARN

# ================= JWT =================
JWT_SECRET=Tz+2x9a5bB8WbB4X3gK9l/oM6eY0V7hP4rZcX9wT1jE=

